trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- checkout: none
- task: SelectiveCheckout@0
  inputs:
    pathsToCheckout: 'UnitTests/obj'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'build'
#     projects: '**/Ball-sorting-puzzle.csproj'
#   displayName: 'Building'

# - task: DotNetCoreCLI@2
#   inputs:
#     command: 'test'
#   displayName: 'Testing'