trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/Ball-sorting-puzzle.csproj'
  displayName: 'Building'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
  displayName: 'Testing'